language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.5
    - python: 3.6


# solution based on https://gist.github.com/dan-blanchard/7045057
# setup anaconda to install scipy and numpy easily and quickly
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    # are not specific to using mini
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # some useful libraries to compile numpy/scipy
    # - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo $TRAVIS_PYTHON_VERSION
  - echo $GOROOT
  - echo $GOPATH
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_tools.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_dev.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION  coverage
  - pip install .
  - pip install pygatb --no-deps

  # install squizz which is a dependency but which is not packaged in conda
  -
  #- mkdir -p ${HOME}/dependencies/src
  #- cd ${HOME}/dependencies/src
  #- wget ftp://ftp.pasteur.fr/pub/gensoft/projects/squizz/squizz-0.99d.tar.gz
  #- tar -xzf squizz-0.99d.tar.gz
  #- cd squizz-0.99d
  #- ./configure --prefix=${HOME}/dependencies/
  #- make
  #- make install
  #- export PATH=${PATH}:${HOME}/dependencies/bin/
  #- cd ${TRAVIS_BUILD_DIR}


# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=bioconvert --cov-report term --timeout 300 -n 2


after_success:
  coveralls
