name: bioconvert

channels:
- bioconda
- conda-forge
- defaults
- r

dependencies:
- python=3.5.0
- colorlog
- biopython
- numpy
- matplotlib
- pandas
- scipy
- pysam
- pillow
- easydev>=0.9.34
- pip
- ruamel.yaml<=0.15.0
- graphviz=2.38
- pygraphviz
- bedtools          # used in gallery and bam2bed


- pip:
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

